apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "mysql-pvc-2"
  namespace: mysql-db
spec:
  storageClassName: mysql-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi