apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-sc
  namespace: mysql-db
provisioner: ebs.csi.aws.com
parameters:
  type: gp2
  fsType: xfs
volumeBindingMode: WaitForFirstConsumer