apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-pvc
  namespace: web-ns
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi