apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sc-pvc
  namespace: web-ns
spec:
  storageClassName: web-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi