apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: john-rb
  namespace: web-apps
subjects:
- kind: User
  name: john
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-deployment-service-reader
  apiGroup: rbac.authorization.k8s.io